using PancakeDevs.ApexPhysics;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace PancakeDevs.ApexPhysics.Editor
{
    [CustomEditor(typeof(ApexPhysicalHumanoid))]
    public sealed class ApexPhysicalHumanoidEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            ApexPhysicalHumanoid humanoid = (ApexPhysicalHumanoid)target;

            EditorGUILayout.LabelField("Apex PC Physical Character", EditorStyles.boldLabel);
            EditorGUILayout.HelpBox(
                "The 0.3.x character workflow is desktop/PC only. This root owns one PC character motor, one animated target, one physical body, NavMesh AI, ragdoll, and recovery.",
                MessageType.Info);

            EditorGUILayout.Space();
            EditorGUILayout.EnumPopup("Generated Mode", humanoid.Mode);
            EditorGUILayout.ObjectField(
                "Physical Character",
                humanoid.PhysicalCharacter,
                typeof(GameObject),
                true);
            EditorGUILayout.ObjectField(
                "Animated Target",
                humanoid.AnimatedTargetCharacter,
                typeof(GameObject),
                true);
            EditorGUILayout.ObjectField(
                "Target Animator",
                humanoid.TargetAnimator,
                typeof(Animator),
                true);

            if (humanoid.Mode != ApexPhysicalHumanoidMode.PhysicalNPC)
            {
                EditorGUILayout.HelpBox(
                    "This is legacy non-PC-NPC content. VR/player conversion is postponed and is not supported by the 0.3.x builder.",
                    MessageType.Warning);
                return;
            }

            ApexPCPhysicalCharacter character = humanoid.PCPhysicalCharacter != null
                ? humanoid.PCPhysicalCharacter
                : humanoid.GetComponent<ApexPCPhysicalCharacter>();

            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Unified Controller", EditorStyles.boldLabel);
            EditorGUILayout.ObjectField(
                "PC Physical Character",
                character,
                typeof(ApexPCPhysicalCharacter),
                true);

            if (character == null)
            {
                EditorGUILayout.HelpBox(
                    "This NPC was generated by an older Apex version. Install the unified PC character controller.",
                    MessageType.Warning);

                if (GUILayout.Button("Install PC Physical Character", GUILayout.Height(36f)))
                {
                    Undo.RecordObject(humanoid, "Install Apex PC Physical Character");
                    character = Undo.AddComponent<ApexPCPhysicalCharacter>(humanoid.gameObject);
                    character.Configure(humanoid);
                    EditorUtility.SetDirty(humanoid);
                    EditorUtility.SetDirty(character);
                    MarkSceneDirty(humanoid);
                }

                return;
            }

            EditorGUILayout.Toggle("Ready", character.IsReady);
            EditorGUILayout.EnumPopup("State", character.State);
            EditorGUILayout.Toggle("Grounded", character.Grounded);
            EditorGUILayout.ObjectField("Motor Body", character.MotorBody, typeof(Rigidbody), true);

            if (!Application.isPlaying)
            {
                if (GUILayout.Button("Rebuild PC Physical Character", GUILayout.Height(36f)))
                {
                    Undo.RecordObject(character, "Rebuild Apex PC Physical Character");
                    character.Rebuild();
                    EditorUtility.SetDirty(character);
                    MarkSceneDirty(humanoid);
                }

                return;
            }

            using (new EditorGUILayout.HorizontalScope())
            {
                if (GUILayout.Button("Idle"))
                {
                    character.SetIdle();
                }

                if (GUILayout.Button("Wander"))
                {
                    character.SetWander();
                }

                if (GUILayout.Button("Stagger"))
                {
                    character.Stagger();
                }
            }

            using (new EditorGUILayout.HorizontalScope())
            {
                if (GUILayout.Button("Knock Down"))
                {
                    character.KnockDown();
                }

                if (GUILayout.Button("Get Up"))
                {
                    character.BeginGetUp();
                }

                if (GUILayout.Button("Activate"))
                {
                    character.Activate();
                }
            }

            Repaint();
        }

        private static void MarkSceneDirty(ApexPhysicalHumanoid humanoid)
        {
            if (humanoid != null && humanoid.gameObject.scene.IsValid())
            {
                EditorSceneManager.MarkSceneDirty(humanoid.gameObject.scene);
            }
        }
    }
}
